module.exports = (seller) => [
  {
    sellerId: seller._id,
    name: "Jersey",
    slug: "jersey",
    category: "Clothing",
    brand: "Generic",
    price: 25,
    stock: 20,
    discount: 5,
    description: "Comfortable sports jersey",
    shopName: seller.shopInfo.shopName,
    images: ["http://localhost:5000/images/products/1.webp"],
  },
  {
    sellerId: seller._id,
    name: "Headphone",
    slug: "headphone",
    category: "Electronics",
    brand: "Generic",
    price: 50,
    stock: 15,
    discount: 10,
    description: "High quality sound headphones",
    shopName: seller.shopInfo.shopName,
    images: ["http://localhost:5000/images/products/2.webp"],
  },
  {
    sellerId: seller._id,
    name: "Bag",
    slug: "bag",
    category: "Accessories",
    brand: "Generic",
    price: 30,
    stock: 18,
    discount: 7,
    description: "Stylish and durable bag",
    shopName: seller.shopInfo.shopName,
    images: ["http://localhost:5000/images/products/3.webp"],
  },
  {
    sellerId: seller._id,
    name: "Shirt",
    slug: "shirt",
    category: "Clothing",
    brand: "Generic",
    price: 20,
    stock: 25,
    discount: 5,
    description: "Casual wear shirt",
    shopName: seller.shopInfo.shopName,
    images: ["http://localhost:5000/images/products/4.webp"],
  },
  {
    sellerId: seller._id,
    name: "Panjabi",
    slug: "panjabi",
    category: "Clothing",
    brand: "Generic",
    price: 35,
    stock: 12,
    discount: 6,
    description: "Traditional panjabi outfit",
    shopName: seller.shopInfo.shopName,
    images: ["http://localhost:5000/images/products/5.webp"],
  },
  {
    sellerId: seller._id,
    name: "T-shirt",
    slug: "t-shirt",
    category: "Clothing",
    brand: "Generic",
    price: 15,
    stock: 30,
    discount: 4,
    description: "Comfortable cotton t-shirt",
    shopName: seller.shopInfo.shopName,
    images: ["http://localhost:5000/images/products/6.webp"],
  },
  {
    sellerId: seller._id,
    name: "Umbrella",
    slug: "umbrella",
    category: "Accessories",
    brand: "Generic",
    price: 10,
    stock: 40,
    discount: 3,
    description: "Waterproof umbrella",
    shopName: seller.shopInfo.shopName,
    images: ["http://localhost:5000/images/products/7.webp"],
  },
];
