module.exports = (seller) => [
  {
    sellerId: seller._id,
    name: "iPhone 14 Pro",
    slug: "iphone-14-pro",
    category: "Mobile",
    brand: "Apple",
    price: 1200,
    stock: 10,
    discount: 5,
    description: "Latest Apple iPhone with A16 chip and Pro camera system",
    shopName: seller.shopInfo.shopName,
    images: ["iphone14pro.jpg"],
  },
  {
    sellerId: seller._id,
    name: "Samsung Galaxy S23 Ultra",
    slug: "samsung-s23-ultra",
    category: "Mobile",
    brand: "Samsung",
    price: 1100,
    stock: 12,
    discount: 8,
    description: "Flagship Samsung phone with 200MP camera",
    shopName: seller.shopInfo.shopName,
    images: ["s23ultra.jpg"],
  },
  {
    sellerId: seller._id,
    name: "MacBook Air M2",
    slug: "macbook-air-m2",
    category: "Laptop",
    brand: "Apple",
    price: 1500,
    stock: 5,
    discount: 10,
    description: "Lightweight Apple laptop with M2 chip",
    shopName: seller.shopInfo.shopName,
    images: ["macbookairm2.jpg"],
  },
  {
    sellerId: seller._id,
    name: "Dell XPS 13",
    slug: "dell-xps-13",
    category: "Laptop",
    brand: "Dell",
    price: 1300,
    stock: 7,
    discount: 7,
    description: "Premium ultrabook with InfinityEdge display",
    shopName: seller.shopInfo.shopName,
    images: ["dellxps13.jpg"],
  },
  {
    sellerId: seller._id,
    name: "Sony WH-1000XM5",
    slug: "sony-wh-1000xm5",
    category: "Headphones",
    brand: "Sony",
    price: 400,
    stock: 20,
    discount: 12,
    description: "Industry leading noise cancelling headphones",
    shopName: seller.shopInfo.shopName,
    images: ["sonyxm5.jpg"],
  },
];
